version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/DharmaOfCode/tenago

    steps:
      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: GOOS=windows go get -u github.com/spf13/cobra

      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...

      - deploy:
          name: deploy release to GitHub
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              gox -output "dist/tenago_{{.OS}}_{{.Arch}}" &&
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/
            else
              echo "Not master branch, dry run only"
            fi